// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuN-_5JPMhxOHsQRqKUilconPE4QAREHA',
    appId: '1:262531591859:web:b39cba342069b6f5310ac6',
    messagingSenderId: '262531591859',
    projectId: 'resturent-7edf0',
    authDomain: 'resturent-7edf0.firebaseapp.com',
    storageBucket: 'resturent-7edf0.firebasestorage.app',
    measurementId: 'G-L8B5LC3WEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm2P71Zpk8YaQG1-Kp7VxGLUNe6PHn1Jw',
    appId: '1:262531591859:android:5ed090aeaf700366310ac6',
    messagingSenderId: '262531591859',
    projectId: 'resturent-7edf0',
    storageBucket: 'resturent-7edf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClVF_c3A4ZVmRITGrgi0yX1nvrLn0t81E',
    appId: '1:262531591859:ios:65c9c4f9cef778a2310ac6',
    messagingSenderId: '262531591859',
    projectId: 'resturent-7edf0',
    storageBucket: 'resturent-7edf0.firebasestorage.app',
    iosBundleId: 'com.example.resturentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClVF_c3A4ZVmRITGrgi0yX1nvrLn0t81E',
    appId: '1:262531591859:ios:65c9c4f9cef778a2310ac6',
    messagingSenderId: '262531591859',
    projectId: 'resturent-7edf0',
    storageBucket: 'resturent-7edf0.firebasestorage.app',
    iosBundleId: 'com.example.resturentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuN-_5JPMhxOHsQRqKUilconPE4QAREHA',
    appId: '1:262531591859:web:a2fa52d9fa1f57ab310ac6',
    messagingSenderId: '262531591859',
    projectId: 'resturent-7edf0',
    authDomain: 'resturent-7edf0.firebaseapp.com',
    storageBucket: 'resturent-7edf0.firebasestorage.app',
    measurementId: 'G-07FMXPPM6H',
  );
}
